export type Realm = {
    realmName: string;
  };
  
  export const realms: Realm[] = [
    { realmName: "Alexstrasza" },
    { realmName: "Alleria" },
    { realmName: "Blackhand" },
    { realmName: "Dalaran" },
    { realmName: "Dentarg" },
    { realmName: "Galakrond" },
    { realmName: "Garona" },
    { realmName: "Ghostlands" },
    { realmName: "Goldrinn" },
    { realmName: "Hellscream" },
    { realmName: "Illidan" },
    { realmName: "Kael'thas" },
    { realmName: "Khadgar" },
    { realmName: "Kirin Tor" },
    { realmName: "Nemesis" },
    { realmName: "Ravencrest" },
    { realmName: "Sentinels" },
    { realmName: "Steamwheedle Cartel" },
    { realmName: "Stormreaver" },
    { realmName: "Terokkar" },
    { realmName: "Thrall" },
    { realmName: "Uldaman" },
    { realmName: "Whisperwind" },
    { realmName: "Zangarmarsh" },
    { realmName: "Agamaggan" },
    { realmName: "Andorhal" },
    { realmName: "Archimonde" },
    { realmName: "Azralon" },
    { realmName: "Azuremyst" },
    { realmName: "Baelgun" },
    { realmName: "Blackwing Lair" },
    { realmName: "Burning Legion" },
    { realmName: "Coilfang" },
    { realmName: "Dalvengyr" },
    { realmName: "Dark Iron" },
    { realmName: "Deathwing" },
    { realmName: "Demon Soul" },
    { realmName: "Dethecus" },
    { realmName: "Detheroc" },
    { realmName: "Doomhammer" },
    { realmName: "Emerald Dream" },
    { realmName: "Eredar" },
    { realmName: "Executus" },
    { realmName: "Gnomeregan" },
    { realmName: "Gorefiend" },
    { realmName: "Greymane" },
    { realmName: "Haomarush" },
    { realmName: "Jaedenar" },
    { realmName: "Kalecgos" },
    { realmName: "Lethon" },
    { realmName: "Lightninghoof" },
    { realmName: "Maelstrom" },
    { realmName: "Moonrunner" },
    { realmName: "Ravenholdt" },
    { realmName: "Sargeras" },
    { realmName: "Scilla" },
    { realmName: "Shadowmoon" },
    { realmName: "Shattered Halls" },
    { realmName: "Shattered Hand" },
    { realmName: "Spinebreaker" },
    { realmName: "Staghelm" },
    { realmName: "Tanaris" },
    { realmName: "The Underbog" },
    { realmName: "The Venture Co" },
    { realmName: "Tol Barad" },
    { realmName: "Twisting Nether" },
    { realmName: "Ursin" },
    { realmName: "Wildhammer" },
    { realmName: "Zuluhed" },
    { realmName: "Altar of Storms" },
    { realmName: "Alterac Mountains" },
    { realmName: "Anetheron" },
    { realmName: "Anvilmar" },
    { realmName: "Argent Dawn" },
    { realmName: "Arthas" },
    { realmName: "Azgalor" },
    { realmName: "Azshara" },
    { realmName: "Balnazzar" },
    { realmName: "Black Dragonflight" },
    { realmName: "Bleeding Hollow" },
    { realmName: "Blood Furnace" },
    { realmName: "Bloodhoof" },
    { realmName: "Dawnbringer" },
    { realmName: "Destromath" },
    { realmName: "Durotan" },
    { realmName: "Duskwood" },
    { realmName: "Elune" },
    { realmName: "Exodar" },
    { realmName: "Gallywix" },
    { realmName: "Gilneas" },
    { realmName: "Gorgonnash" },
    { realmName: "Grizzly Hills" },
    { realmName: "Gul'dan" },
    { realmName: "Lothar" },
    { realmName: "Madoran" },
    { realmName: "Magtheridon" },
    { realmName: "Malfurion" },
    { realmName: "Mannoroth" },
    { realmName: "Medivh" },
    { realmName: "Nazjatar" },
    { realmName: "Skullcrusher" },
    { realmName: "Stormrage" },
    { realmName: "The Forgotten Coast" },
    { realmName: "The Scryers" },
    { realmName: "Thunderlord" },
    { realmName: "Trollbane" },
    { realmName: "Undermine" },
    { realmName: "Warsong" },
    { realmName: "Ysera" },
    { realmName: "Ysondre" },
    { realmName: "Zul'jin" },
    { realmName: "Aerie Peak" },
    { realmName: "Aggramar" },
    { realmName: "Area 52" },
    { realmName: "Arygos" },
    { realmName: "Auchindoun" },
    { realmName: "Blade's Edge" },
    { realmName: "Burning Blade" },
    { realmName: "Cho'gall" },
    { realmName: "Drakkari" },
    { realmName: "Earthen Ring" },
    { realmName: "Eonar" },
    { realmName: "Fizzcrank" },
    { realmName: "Icecrown" },
    { realmName: "Kargath" },
    { realmName: "Kel'Thuzad" },
    { realmName: "Laughing Skull" },
    { realmName: "Lightning's Blade" },
    { realmName: "Llane" },
    { realmName: "Mal'Ganis" },
    { realmName: "Malygos" },
    { realmName: "Norgannon" },
    { realmName: "Onyxia" },
    { realmName: "Quel'Thalas" },
    { realmName: "Ragnaros" },
    { realmName: "Thunderhorn" },
    { realmName: "Turalyon" },
    { realmName: "Velen" },
    { realmName: "Blackrock" },
    { realmName: "Farstriders" },
    { realmName: "Frostwolf" },
    { realmName: "Kil'jaeden" },
    { realmName: "Kilrogg" },
    { realmName: "Nazgrel" },
    { realmName: "Nesingwary" },
    { realmName: "Proudmoore" },
    { realmName: "Quel'dorei" },
    { realmName: "Sen'jin" },
    { realmName: "Silver Hand" },
    { realmName: "Thorium Brotherhood" },
    { realmName: "Tichondrius" },
    { realmName: "Vashj" },
    { realmName: "Vek'nilash" },
    { realmName: "Winterhoof" },
    { realmName: "Aegwynn" },
    { realmName: "Anub'arak" },
    { realmName: "Bladefist" },
    { realmName: "Bonechewer" },
    { realmName: "Chromaggus" },
    { realmName: "Crushridge" },
    { realmName: "Daggerspine" },
    { realmName: "Eitrigg" },
    { realmName: "Garithos" },
    { realmName: "Garrosh" },
    { realmName: "Gurubashi" },
    { realmName: "Hakkar" },
    { realmName: "Hyjal" },
    { realmName: "Korgath" },
    { realmName: "Kul Tiras" },
    { realmName: "Misha" },
    { realmName: "Muradin" },
    { realmName: "Nathrezim" },
    { realmName: "Nordrassil" },
    { realmName: "Rexxar" },
    { realmName: "Runetotem" },
    { realmName: "Sisters of Elune" },
    { realmName: "Spirestone" },
    { realmName: "Stormscale" },
    { realmName: "Suramar" },
    { realmName: "Terenas" },
    { realmName: "Tortheldrin" },
    { realmName: "Uther" },
    { realmName: "Venture Co" },
    { realmName: "Warsong Gulch" },
    { realmName: "Windrunner" },
    { realmName: "World Tree" },
    { realmName: "Zandalar Tribe" }
  ];
  